name: GiveTo
main: ltguide.giveto.GiveTo
version: 0.61
author: ltguide
description: Give Items
commands:
  giveme:
    description: Give Items to Self
    aliases: gme
    usage: /<command> <item> [count]
  giveto:
    description: Give Items to Others
    aliases: [gto,give]
    usage: /<command> <player> <item> [count]